In [8]:
import numpy as np
import time

In [11]:
#Performance evaluation
size = 1_000_000

#Python list
py_list = list(range(size))

start_time = time.time()
sq_list = [x**2 for x in py_list]
end_time = time.time()

print(f"The time taken by python list : {end_time - start_time}")

#Numpy array
np_array = np.array(py_list)

start_time = time.time()
sq_array = np_array ** 2
end_time = time.time()

print(f"The time taken by python list : {end_time - start_time}")

The time taken by python list : 0.1573171615600586
The time taken by python list : 0.007038116455078125


In [15]:
# Memory 
import sys 

print(f"python list size ={sys.getsizeof(py_list) * len(py_list)} bytes")

print(f"npArray size : {np_array.nbytes} bytes")

python list size =8000056000000 bytes
npArray size : 8000000 bytes


In [18]:
# numpy arrays using list

# 1D
np_array = np.array([1,2,3,4])
print(np_array)
print(np_array.dtype) # Type of np-array
print(np_array.shape) # Dimension of np-array ( m * n ) m-> rows  n-> columns

# 2D
np_array = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(np_array)
print(np_array.dtype) # Type of np-array
print(np_array.shape) # Dimension of np-array ( m * n ) m-> rows  n-> columns

[1 2 3 4]
int64
(4,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
int64
(4, 3)


In [35]:
# Creating np-arrays using build-in fuctions or from scratch

# to fill array with zeros
array = np.zeros((3,4))
print(array)
print(array.dtype)
print(array.shape)

# to fill array with ones
array = np.ones((3,4),dtype="int64")
print(array)
print(array.dtype)
print(array.shape)

# to fill with a specific value
array = np.full((3,4),100)
print(array)
print(array.dtype)
print(array.shape)

# to create a identity matrix
array = np.eye(4 , dtype="int64")
print(array)
print(array.dtype)
print(array.shape)

# to fill values in range(start,end,step)
array = np.arange(0,10,4)
print(array)
print(array.dtype)
print(array.shape)

# to get evenly spaced element in a range
array = np.linspace(0,100,4,dtype = "int64")
print(array)
print(array.dtype)
print(array.shape)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64
(3, 4)
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int64
(3, 4)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
int64
(3, 4)
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
int64
(4, 4)
[0 4 8]
int64
(3,)
[  0  33  66 100]
int64
(4,)


In [42]:
# Properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

#To print the dimension of an array 
print(arr.shape)

#To print the data type of an array
print(arr.dtype)

#To print the total number of elements
print(arr.size)

#To print the number of dimensions
print(arr.ndim)

#To change the data type of an array
float_arr = arr.astype(np.float64)
print(float_arr)
print(float_arr.dtype)

(4, 3)
int64
12
2
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
float64


In [45]:
# Reshaping an array 
arr = np.array([[1,2,3],[4,5,6]])

# To reshape or to get transpose of 2D array
reshaped_arr = arr.reshape((3,2))
print(reshaped_arr)
print(reshaped_arr.shape)

# To convert 2D array to 1D array
flattened_arr = arr.flatten()
print(flattened_arr)
print(flattened_arr.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[1 2 3 4 5 6]
(6,)


In [58]:
#Indexing 
arr = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([1,2,3,4,5])
#Normal Indexing
print(arr[0][2])

#Fancy Indexing (to get many index value at once) 

# On 1D array
idx = [0,2,4]
print(arr2[idx])

# On 2D array
# for [[0,0],[1,0],[1,1]]
rows = [0,1,1]
columns = [0,0,1]

print(arr[rows,columns])

#Boolean Indexing - to specify a specific condition 
print(arr2[arr2 > 2])


3
[1 3 5]
[1 4 5]
[3 4 5]


In [59]:
# Slicing [start:end:step]
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr[0:6:2])

[1 3 5]


In [63]:
#View vs copy 

# Python list ( it creates a new copy of original list for sublist)
py_list = [1,2,3,4,5,6,7]
sublist = py_list[1:5]
sublist[0] = 200
print(sublist)
print(py_list)

# NumPy array doesn't create a new copy instead it points to the original array
np_array = np.array([1,2,3,4,5,6,7])
sub_arr = np_array[1:5]
sub_arr[0] = 200
print(sub_arr)
print(np_array)

# If want to create a copy of the view of the original array 
sub_array = np_array[1:5].copy()
print(sub_array)

[200, 3, 4, 5]
[1, 2, 3, 4, 5, 6, 7]
[200   3   4   5]
[  1 200   3   4   5   6   7]
[200   3   4   5]


In [66]:
#Axis use in 2D arrays
array = np.array([[1,2,3]
                  ,[4,5,6]
                  ,[7,8,9]]
                )

# for 2D array to perfrom operation on rows use axis = 1 and for columns axis = 0

# for the sum of all the rows use axis = 1
sum_of_rows = np.sum(array,axis = 1)
print(sum_of_rows)

# for the sum of all the columns use axis = 0
sum_of_columns = np.sum(array,axis = 0)
print(sum_of_columns)




[ 6 15 24]
[12 15 18]


In [72]:
# 3D array 
array = np.array([[[1,2]
                  ,[3,4]
                  ,[5,6]]
            ,[[7,8]
            ,[9,10]
            ,[11,12]]])

#Indexing 
print(array[0][1][1])

#Slicing
print(array[1:2,1:2,0:2])

4
[[[ 9 10]]]


In [75]:
#Vectorization (performing operations without using loops)

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr1 + arr2)
print(arr1 ** 2 )

[ 7  9 11 13 15]
[ 1  4  9 16 25]


In [81]:
#Broadcasting (Scalling smaller values into bigger one so that shape of the value doesn't matter)

arr = np.array([1,2,3,4,5])
arr2= arr + 1
print(arr2)


arr1 = np.array([[1,2],[3,4],[5,6]])
arr2 = np.array([[4,5]])

print(arr1 + arr2)

[2 3 4 5 6]
[[ 5  7]
 [ 7  9]
 [ 9 11]]


In [84]:
#Normalization 

arr1 = np.array([[66,75],[53,86]])

mean = np.mean(arr1)
st_deviation = np.std(arr1)

normalized_arr = (arr1 - mean)/st_deviation
print(normalized_arr)

[[-0.33047695  0.41309619]
 [-1.40452705  1.32190782]]
