In [3]:
import numpy as np
import time

In [3]:
# Execution performance of python lists and npArrays (comparing performance in terms of time)
# Python list
size=10_000_000
py_list=list(range(size))

start=time.time()
sq_list=[x**2 for x in py_list]
end=time.time()

print(f"time for python list {end-start} seconds") 

# Np arrays
np_array=np.array(py_list)

start=time.time()
sq_array=np_array**2
end=time.time()

print(f"time for python array {end-start} seconds")

time for python list 1.639601469039917 seconds
time for python array 0.03857064247131348 seconds


In [5]:
# Performance in terms of memory 
import sys

print(f"python list size ={sys.getsizeof(py_list) * len(py_list)} bytes")

print(f"np array size ={np_array.nbytes} bytes")

python list size =800000560000000 bytes
np array size =80000000 bytes


In [10]:
# Np array creation (we usually create np array using list)
arr= np.array([1,2,3,4])
print(arr,type(arr),arr.shape)

# 2D npArray
arr2D=np.array([[2,3,4],[5,6,7],[8,9,0]])
print(arr2D,type(arr2D),arr2D.shape)

[1 2 3 4] <class 'numpy.ndarray'> (4,)
[[2 3 4]
 [5 6 7]
 [8 9 0]] <class 'numpy.ndarray'> (3, 3)


In [23]:
# Create np arrat from scratch

# 1-Using zeros(initialize the np array with zeros)
arr1=np.zeros((2,3),dtype="int64")
print(arr1,arr1.shape)

# 2-Using ones(initialize the np array with ones)
arr2=np.ones((3,4),dtype="int64")
print(arr2,arr2.shape)

# 3-Using full prefill with values(initialize with the value we provide)
arr3=np.full((3,4),1000)
print(arr3,arr3.shape)

# 4-Using eye (Create an identity matrix) => Diagonal values are 1 only applied on square matrix
arr4=np.eye(3)
print(arr4,arr4.shape)

# 5-Range elements
arr5=np.arange(0,10,2)
print(arr5,arr5.shape)

# 6-Linspace(evenly spaced arrays)
arr6=np.linspace(1,100,4)
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] (3, 4)
[[1000 1000 1000 1000]
 [1000 1000 1000 1000]
 [1000 1000 1000 1000]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[0 2 4 6 8] (5,)
[  1.  34.  67. 100.] (4,)


In [34]:
# Properties
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape) #Dimention of array (m,n)
print(arr.size)  #No. of elements
print(arr.dtype) #Type of value stored
print(arr.ndim)  #No. of dimensions

# To type cast existing np array
float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype) 


(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [42]:
# Operation of np arrays

# Reshape
arr=np.array([[1,2,3],[4,5,6]])

reshaped_arr=arr.reshape(3,2)
print(reshaped_arr,reshaped_arr.shape)

# Flatten (2D => 1D)

flattened_arr=arr.flatten()
print(flattened_arr,flattened_arr.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [53]:
# Indexing
arr=np.array([[1,2,3],[4,5,6]])

# Normal indexing 
print(arr[1][2])

# Fancy indexing
arr=np.array([1,2,3,4,5,6])
idx=[2,3]
print(arr[idx])

# Boolean indexing
print(arr[arr > 3])

6
[3 4]
[4 5 6]


In [56]:
# Slicing
print(arr[1:5])

[2 3 4 5]


In [65]:
# Copy and view in slicing

# Copy (when we use normal python list)
nums=[1,2,3,4]
sub_part=nums[1:3]
print(sub_part)
sub_part[0]=500
print(sub_part)
print(nums)

# View (when we create np array)
arr=np.array([1,2,3,4])
sub_arr=arr[1:3]
print(sub_arr)
sub_arr[0]=500
print(sub_arr)
print(arr)

# we use .copy if we dont want to make changes in the original arr
arr1=np.array([1,2,3,4])
sub_arr1=arr1[1:3].copy()
print(sub_arr1)
sub_arr1[0]=500
print(sub_arr1)
print(arr1)


[2, 3]
[500, 3]
[1, 2, 3, 4]
[2 3]
[500   3]
[  1 500   3   4]
[2 3]
[500   3]
[1 2 3 4]


In [4]:
# Data types 

# Integers
arr=np.array([1,2,3,4,5])
print(arr,arr.dtype)

# Floating
arr=np.array([1,2.0,3,4,5])
print(arr,arr.dtype)

# Boolean(True => 1 , False => 0)
arr=np.array([True,False])
print(arr,arr.dtype)
arr=np.array([1,2,3,4,5,True,False])
print(arr,arr.dtype)

#Complex numbers
arr=np.array([1+2j,4+5j])
print(arr,arr.dtype)

# It is not advisable to store string and object 
# while using numpy because numpy is basically 
# used when we are dealing with numeric values

# String 
arr=np.array([1,2,3,4,5,"Hello"])
print(arr,arr.dtype)

# Object
arr=np.array([1,2,3,4,5,{1,2,3}])
print(arr,arr.dtype)

[1 2 3 4 5] int64
[1. 2. 3. 4. 5.] float64
[ True False] bool
[1 2 3 4 5 1 0] int64
[1.+2.j 4.+5.j] complex128
['1' '2' '3' '4' '5' 'Hello'] <U21
[1 2 3 4 5 {1, 2, 3}] object


In [10]:
# Multi-Dimensional arrays
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

# To print sum of all the elements in array
print(np.sum(arr))

# To print the sum of all the columns
sum_of_columns=np.sum(arr,0)
print(sum_of_columns)

# To print the sum of all the rows
sum_of_rows=np.sum(arr,1)
print(sum_of_rows)

# Can perform slicing 
print(arr[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [23]:
# 3D arrays 
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[:,:,:])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [39]:
# Vectorization
arr1=np.array([1,2,3,4,5])
arr2=np.array([1,2,3,4,5])
print(arr1**2)
print(arr1+arr2)


# Broadcasting
arr1=np.array([[1,2],[3,4],[5,6]])
arr2=np.array([[2]])
arr3=np.array([[1,2],[3,4],[5,6]])
print(arr1 + arr2)
print(arr1*arr3)

[ 1  4  9 16 25]
[ 2  4  6  8 10]
[[3 4]
 [5 6]
 [7 8]]
[[ 1  4]
 [ 9 16]
 [25 36]]


In [45]:
# Normalization

arr=np.array([[1,2],[3,4]])

mean=arr.mean()
print(mean)

std=arr.std()
print(std)

normalized_arr=(arr-mean)/std
print(normalized_arr)

2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [73]:
# Mathematical functions

# Aggregation
arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.median(arr))
print(np.argmin(arr)) # index of min value
print(np.argmax(arr)) # index of max value

# power
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,2))


# Log & Exponential
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))


# Rounding
arr=np.array([1,1.4,2.5,-3,4.3,3.8,7,9])
print(np.round(arr))
print(np.floor(arr))
print(np.ceil(arr))
print(np.trunc(arr))


# Extras
print(np.sort(arr))
print(np.unique(arr))
print(np.abs(arr))

15
120
1
5
3.0
1.4142135623730951
2.0
3.0
0
4
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[ 1  4  9 16 25]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 1.  1.  2. -3.  4.  4.  7.  9.]
[ 1.  1.  2. -3.  4.  3.  7.  9.]
[ 1.  2.  3. -3.  5.  4.  7.  9.]
[ 1.  1.  2. -3.  4.  3.  7.  9.]
[-3.   1.   1.4  2.5  3.8  4.3  7.   9. ]
[-3.   1.   1.4  2.5  3.8  4.3  7.   9. ]
[1.  1.4 2.5 3.  4.3 3.8 7.  9. ]
